cache: pip

matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic
      env: NAME="Python 3.5"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 3.5.6
        - pyenv local 3.5.6
        - eval "$(pyenv init -)"
        - python3 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 3.6"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 3.6.6
        - pyenv local 3.6.6
        - eval "$(pyenv init -)"
        - python3 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 3.7"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 3.7.0
        - pyenv local 3.7.0
        - eval "$(pyenv init -)"
        - python3 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python pypy3"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install pypy3.5-6.0.0
        - pyenv local pypy3.5-6.0.0
        - eval "$(pyenv init -)"
        - pypy3 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 3.6-dev"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 3.6-dev
        - pyenv local 3.6-dev
        - eval "$(pyenv init -)"
        - python3 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 3.7-dev"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 3.7-dev
        - pyenv local 3.7-dev
        - eval "$(pyenv init -)"
        - python3 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 3.8-dev"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 3.8-dev
        - pyenv local 3.8-dev
        - eval "$(pyenv init -)"
        - python3 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: &python_major_ver 3.7
      dist: xenial
      sudo: true
    - os: linux
      language: python
      python: 3.6-dev
    - os: linux
      language: python
      python: 3.7-dev
      dist: xenial
      sudo: true
    - os: linux
      language: python
      python: 3.8-dev
      dist: xenial
      sudo: true
    - os: linux
      language: python
      python: pypy3
  allow_failures:
    - os: osx
      env: NAME="Python 3.6-dev"
    - os: osx
      env: NAME="Python 3.7-dev"
    - os: osx
      env: NAME="Python 3.8-dev"
    - os: linux
      python: 3.6-dev
    - os: linux
      python: 3.7-dev
    - os: linux
      python: 3.8-dev

install:
- curl https://bootstrap.pypa.io/get-pip.py | python
- python -m pip install --upgrade wheel>=0.30.0 setuptools>=36.6.0

script:
- python -m unittest --verbose test
- "[[ $(python -c \"import platform; print(platform.python_implementation())\") == \"CPython\" ]] && PYTHONASYNCIODEBUG=1 python -m unittest test || true"

deploy:
  provider: pypi
  user: martius
  password:
    secure: "UP31EYyU/X5NlCStj80Jc9j2DKsJDe9ErsEaqaPkVi1rV8AASt38gO8qA/hcW+f56qRE34qjeaYL+vHJ6nT7wRcWWu1HU4gp4+C6THEOlNVdgB4AzaqOtNF1T6ArPXoMrKWO2sPwcLrAIls8DCzYkdYGmbtFOXGDl4n7ZubJoM8="
  distributions: sdist bdist_wheel
  on: # Only when a tag is on master and matches vX.Y.Z
    python: *python_major_ver
    tags: true
    branch: master
    condition: '$TRAVIS_TAG =~ ^v([0-9]+\.){2}[0-9]+$'
